using TheLeague.Core.Enums;

namespace TheLeague.Core.Entities;

/// <summary>
/// Defines a fee that can be charged to members.
/// Supports various fee types with flexible pricing and scheduling.
/// </summary>
public class Fee
{
    public Guid Id { get; set; }
    public Guid ClubId { get; set; }

    // Basic Information
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? Code { get; set; } // Internal fee code
    public FeeType Type { get; set; }

    // Pricing
    public decimal Amount { get; set; }
    public decimal? MinAmount { get; set; } // For variable fees
    public decimal? MaxAmount { get; set; }
    public string Currency { get; set; } = "GBP";
    public bool IsTaxable { get; set; }
    public decimal? TaxRate { get; set; } // e.g., 20 for 20%

    // Frequency & Scheduling
    public FeeFrequency Frequency { get; set; } = FeeFrequency.OneTime;
    public int? FrequencyInterval { get; set; } // Every N periods
    public DateTime? EffectiveFrom { get; set; }
    public DateTime? EffectiveUntil { get; set; }
    public int? DueDayOfMonth { get; set; } // For monthly fees

    // Late Payment
    public bool HasLateFee { get; set; }
    public decimal? LateFeeAmount { get; set; }
    public decimal? LateFeePercentage { get; set; }
    public int? GracePeriodDays { get; set; }
    public int? LateFeeStartDay { get; set; } // Days after due date

    // Applicability
    public bool AppliesToAll { get; set; } = true;
    public string? ApplicableMembershipTypes { get; set; } // JSON array of membership type IDs
    public string? ApplicableMemberCategories { get; set; } // JSON array
    public int? MinAge { get; set; }
    public int? MaxAge { get; set; }

    // Discounts
    public bool AllowEarlyPaymentDiscount { get; set; }
    public decimal? EarlyPaymentDiscountPercent { get; set; }
    public int? EarlyPaymentDays { get; set; } // Days before due to qualify

    // Payment Options
    public bool AllowPartialPayment { get; set; }
    public bool AllowPaymentPlan { get; set; }
    public int? MaxInstallments { get; set; }
    public bool IsRefundable { get; set; } = true;
    public int? RefundableDays { get; set; } // Days within which refund is allowed

    // Automation
    public bool AutoGenerate { get; set; } // Auto-generate invoices
    public int? AutoGenerateDaysBefore { get; set; } // Days before due date to generate
    public bool AutoRemind { get; set; }
    public string? ReminderSchedule { get; set; } // JSON: [{"daysBefore": 7}, {"daysBefore": 3}]

    // Status
    public bool IsActive { get; set; } = true;
    public bool IsRequired { get; set; } // Mandatory fee
    public bool IsHidden { get; set; } // Hidden from member portal
    public int SortOrder { get; set; }

    // GL/Accounting
    public string? GLAccountCode { get; set; }
    public string? CostCenter { get; set; }
    public string? TaxCode { get; set; }

    // Metadata
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }
    public string? CreatedBy { get; set; }
    public string? UpdatedBy { get; set; }

    // Navigation
    public Club Club { get; set; } = null!;
    public ICollection<Payment> Payments { get; set; } = new List<Payment>();
}
