using TheLeague.Core.Enums;

namespace TheLeague.Core.Entities;

/// <summary>
/// Represents a journal entry for double-entry bookkeeping.
/// Each entry must have balanced debits and credits.
/// </summary>
public class JournalEntry
{
    public Guid Id { get; set; }
    public Guid ClubId { get; set; }
    public Guid FiscalPeriodId { get; set; }

    // Entry Details
    public string EntryNumber { get; set; } = string.Empty;
    public DateTime EntryDate { get; set; }
    public string Description { get; set; } = string.Empty;
    public string? Reference { get; set; }
    public string? Memo { get; set; }

    // Amounts
    public decimal TotalDebit { get; set; }
    public decimal TotalCredit { get; set; }
    public string Currency { get; set; } = "GBP";

    // Status
    public JournalEntryStatus Status { get; set; } = JournalEntryStatus.Draft;
    public bool IsBalanced { get; set; }
    public bool IsAdjusting { get; set; } // Adjusting entry
    public bool IsClosing { get; set; } // Closing entry
    public bool IsReversing { get; set; } // Reversing entry
    public Guid? ReversedFromId { get; set; } // If this reverses another entry
    public Guid? ReversedById { get; set; } // If this was reversed by another entry
    public DateTime? ReversalDate { get; set; }

    // Source Tracking
    public string? SourceType { get; set; } // Payment, Invoice, Manual, Import, etc.
    public Guid? SourceId { get; set; }
    public string? SourceReference { get; set; }
    public bool IsAutoGenerated { get; set; }

    // Approval Workflow
    public bool RequiresApproval { get; set; }
    public string? PreparedBy { get; set; }
    public DateTime? PreparedDate { get; set; }
    public string? ApprovedBy { get; set; }
    public DateTime? ApprovedDate { get; set; }
    public string? PostedBy { get; set; }
    public DateTime? PostedDate { get; set; }
    public string? VoidedBy { get; set; }
    public DateTime? VoidedDate { get; set; }
    public string? VoidReason { get; set; }

    // Audit
    public string? LastModifiedBy { get; set; }
    public DateTime? LastModifiedDate { get; set; }
    public int Version { get; set; } = 1;

    // Attachments
    public string? AttachmentUrls { get; set; } // JSON array

    // Notes
    public string? Notes { get; set; }
    public string? InternalNotes { get; set; }

    // Metadata
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }
    public string? CreatedBy { get; set; }

    // Navigation
    public Club Club { get; set; } = null!;
    public FiscalPeriod FiscalPeriod { get; set; } = null!;
    public JournalEntry? ReversedFrom { get; set; }
    public JournalEntry? ReversedBy { get; set; }
    public ICollection<JournalEntryLine> Lines { get; set; } = new List<JournalEntryLine>();
}

/// <summary>
/// Represents a single line item in a journal entry.
/// </summary>
public class JournalEntryLine
{
    public Guid Id { get; set; }
    public Guid JournalEntryId { get; set; }
    public Guid AccountId { get; set; }

    // Line Details
    public int LineNumber { get; set; }
    public string? Description { get; set; }

    // Amounts
    public decimal DebitAmount { get; set; }
    public decimal CreditAmount { get; set; }
    public string Currency { get; set; } = "GBP";

    // Tax
    public Guid? TaxRateId { get; set; }
    public decimal? TaxAmount { get; set; }
    public bool IsTaxInclusive { get; set; }

    // Categorization
    public string? Department { get; set; }
    public string? Project { get; set; }
    public string? CostCenter { get; set; }

    // Related Entity
    public Guid? MemberId { get; set; }
    public Guid? VendorId { get; set; }
    public string? ExternalReference { get; set; }

    // Reconciliation
    public bool IsReconciled { get; set; }
    public DateTime? ReconciledDate { get; set; }
    public Guid? ReconciliationId { get; set; }

    // Navigation
    public JournalEntry JournalEntry { get; set; } = null!;
    public ChartOfAccount Account { get; set; } = null!;
    public TaxRate? TaxRate { get; set; }
    public Member? Member { get; set; }
}
