export interface Fee {
  id: string;
  name: string;
  description?: string;
  code?: string;
  type: FeeType;
  amount: number;
  minAmount?: number;
  maxAmount?: number;
  currency: string;
  isTaxable: boolean;
  taxRate?: number;
  frequency: FeeFrequency;
  frequencyInterval?: number;
  effectiveFrom?: Date;
  effectiveUntil?: Date;
  dueDayOfMonth?: number;
  hasLateFee: boolean;
  lateFeeAmount?: number;
  lateFeePercentage?: number;
  gracePeriodDays?: number;
  appliesToAll: boolean;
  applicableMembershipTypes?: string;
  minAge?: number;
  maxAge?: number;
  allowEarlyPaymentDiscount: boolean;
  earlyPaymentDiscountPercent?: number;
  earlyPaymentDays?: number;
  allowPartialPayment: boolean;
  allowPaymentPlan: boolean;
  maxInstallments?: number;
  isRefundable: boolean;
  refundableDays?: number;
  autoGenerate: boolean;
  autoRemind: boolean;
  isActive: boolean;
  isRequired: boolean;
  isHidden: boolean;
  sortOrder: number;
  glAccountCode?: string;
  costCenter?: string;
  createdAt: Date;
  paymentCount: number;
}

export interface FeeListItem {
  id: string;
  name: string;
  code?: string;
  type: FeeType;
  amount: number;
  currency: string;
  frequency: FeeFrequency;
  isActive: boolean;
  isRequired: boolean;
  sortOrder: number;
  paymentCount: number;
}

export interface FeeCreateRequest {
  name: string;
  type: FeeType;
  amount: number;
  description?: string;
  code?: string;
  minAmount?: number;
  maxAmount?: number;
  currency?: string;
  isTaxable?: boolean;
  taxRate?: number;
  frequency?: FeeFrequency;
  frequencyInterval?: number;
  effectiveFrom?: Date;
  effectiveUntil?: Date;
  dueDayOfMonth?: number;
  hasLateFee?: boolean;
  lateFeeAmount?: number;
  lateFeePercentage?: number;
  gracePeriodDays?: number;
  lateFeeStartDay?: number;
  appliesToAll?: boolean;
  applicableMembershipTypes?: string;
  applicableMemberCategories?: string;
  minAge?: number;
  maxAge?: number;
  allowEarlyPaymentDiscount?: boolean;
  earlyPaymentDiscountPercent?: number;
  earlyPaymentDays?: number;
  allowPartialPayment?: boolean;
  allowPaymentPlan?: boolean;
  maxInstallments?: number;
  isRefundable?: boolean;
  refundableDays?: number;
  autoGenerate?: boolean;
  autoGenerateDaysBefore?: number;
  autoRemind?: boolean;
  reminderSchedule?: string;
  isActive?: boolean;
  isRequired?: boolean;
  isHidden?: boolean;
  sortOrder?: number;
  glAccountCode?: string;
  costCenter?: string;
  taxCode?: string;
}

export interface FeeFilterRequest {
  type?: FeeType;
  frequency?: FeeFrequency;
  isActive?: boolean;
  isRequired?: boolean;
  search?: string;
  page?: number;
  pageSize?: number;
}

export enum FeeType {
  Membership = 'Membership',
  Registration = 'Registration',
  JoiningFee = 'JoiningFee',
  AnnualSubscription = 'AnnualSubscription',
  Activity = 'Activity',
  ClassFee = 'ClassFee',
  EventParticipation = 'EventParticipation',
  FacilityBooking = 'FacilityBooking',
  EquipmentRental = 'EquipmentRental',
  LockerRental = 'LockerRental',
  Coaching = 'Coaching',
  Training = 'Training',
  LatePaymentPenalty = 'LatePaymentPenalty',
  Administration = 'Administration',
  Insurance = 'Insurance',
  GuestPass = 'GuestPass',
  Merchandise = 'Merchandise',
  Other = 'Other'
}

export enum FeeFrequency {
  OneTime = 'OneTime',
  PerSession = 'PerSession',
  Daily = 'Daily',
  Weekly = 'Weekly',
  Monthly = 'Monthly',
  Quarterly = 'Quarterly',
  Biannual = 'Biannual',
  Annual = 'Annual'
}

export const FeeTypeLabels: Record<FeeType, string> = {
  [FeeType.Membership]: 'Membership',
  [FeeType.Registration]: 'Registration',
  [FeeType.JoiningFee]: 'Joining Fee',
  [FeeType.AnnualSubscription]: 'Annual Subscription',
  [FeeType.Activity]: 'Activity',
  [FeeType.ClassFee]: 'Class Fee',
  [FeeType.EventParticipation]: 'Event Participation',
  [FeeType.FacilityBooking]: 'Facility Booking',
  [FeeType.EquipmentRental]: 'Equipment Rental',
  [FeeType.LockerRental]: 'Locker Rental',
  [FeeType.Coaching]: 'Coaching',
  [FeeType.Training]: 'Training',
  [FeeType.LatePaymentPenalty]: 'Late Payment Penalty',
  [FeeType.Administration]: 'Administration',
  [FeeType.Insurance]: 'Insurance',
  [FeeType.GuestPass]: 'Guest Pass',
  [FeeType.Merchandise]: 'Merchandise',
  [FeeType.Other]: 'Other'
};

export const FeeFrequencyLabels: Record<FeeFrequency, string> = {
  [FeeFrequency.OneTime]: 'One Time',
  [FeeFrequency.PerSession]: 'Per Session',
  [FeeFrequency.Daily]: 'Daily',
  [FeeFrequency.Weekly]: 'Weekly',
  [FeeFrequency.Monthly]: 'Monthly',
  [FeeFrequency.Quarterly]: 'Quarterly',
  [FeeFrequency.Biannual]: 'Biannual',
  [FeeFrequency.Annual]: 'Annual'
};
